'PRINTER PORT VIDEO ADAPTER 320 x 200 RES - FULL SCREEN VERSION
CLS: SCREEN 13 '13 = 320 x 200 x 256
FOR I& = 0 TO 63 'SET UP B&W PALETTE
PALETTE (I& * 4) + 7, (65536 * I& + 256 * I& + I&): NEXT I&
COLOR 127
LOCATE 1, 34: PRINT "PRINTER": LOCATE 2, 34: PRINT "PORT"
LOCATE 3, 34: PRINT "VIDEO": LOCATE 4, 34: PRINT "ADAPTER"
LOCATE 6, 34: PRINT "OPTIONS": LOCATE 7, 34: PRINT "Q=QUIT"
LOCATE 8, 34: PRINT "S=SAVE": LOCATE 9, 34: PRINT "V=VIEW"
START: OUT &H37A, 2 'WRITE PICTURE
FOR A = 1 TO 10000: NEXT A 'DELAY FOR V SYNC
OUT &H37A, 4 'READ, RANGE
FOR V = -12 TO 180 'VERTICAL RANGE
    X = X + 1: IF X = 5 THEN X = 1: V = V - 1 'ASPECT RATIO FIX
    PSET (0, V), 0
    FOR H = 0 TO 255 'HORIZONTAL RANGE
        OUT &H37A, 0: OUT &H37A, 1: PSET STEP(1, 0), INP(&H379)
    NEXT H
NEXT V
key$ = INKEY$ 'GET USERS RESOURCES
IF key$ = "Q" OR key$ = "q" THEN END
DIM picture%(0 TO 29000)
IF key$ = "S" OR key$ = "s" THEN
    LOCATE 25, 1: INPUT "NAME"; file$
    GET (0, 0)-(252, 190), picture%()
    DEF SEG = VARSEG(picture%(1))
    BSAVE file$, VARPTR(picture%(1)), 48000
    DEF SEG
END IF
IF key$ = "V" OR key$ = "v" THEN
    LOCATE 25, 1: INPUT "NAME"; file$
    file$ = file$ + ".bas"
    GET (0, 0)-(252, 190), picture%()
    DEF SEG = VARSEG(picture%(1))
    BLOAD file$, VARPTR(picture%(1))
    DEF SEG
    PUT (O, 0), picture%(), PSET
    FOR A = 1 TO 100000: NEXT A 'DELAY FOR VIEWING
END IF
LOCATE 15, 34: PRINT "     ": LOCATE 16, 34: PRINT "     "
GOTO START 'RESTART

